// repromon_vue/src/components/AppHeader.vue
<template>
  <div class="header" style="display: flex; justify-content: space-between;">
    <div>
      <p>&nbsp;<b>ReproMon: </b>{{ screen_name }}</p>
    </div>
    <div>
      <p><b>Time:</b> {{ currentTime }} &nbsp;&nbsp;<b>User:</b> {{ currentUser.first_name }} {{ currentUser.last_name }}&nbsp;</p>
    </div>
  </div>
</template>

<script>
import '@/css/main.css'
import moment from 'moment';
import { LoginService } from '@/service/LoginService.js';
import {AppConfig} from "@/config";

export default {
  name: 'AppHeader',
  props: {
    screen_name: String,
    first_name: String,
    last_name: String
  },
  data() {
    return {
      currentTime: '',
      currentUser: {},
    };
  },
  mounted() {
    this.updateTime();
    setInterval(this.updateTime, 1000);
    this.getCurrentUser();
  },
  methods: {
    updateTime() {
      const now = moment().format('YYYY/MM/DD HH:mm:ss');
      this.currentTime = now;
    },
    async getCurrentUser() {
      try {
        this.currentUser = await LoginService.getCurrentUser();
        AppConfig.CURRENT_USER = this.currentUser
        console.log("set AppConfig.CURRENT_USER="+JSON.stringify(AppConfig.CURRENT_USER))
      } catch (error) {
        console.error('Failed to get current user:', error);
      }
    },
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.header {
  color: white;
  background-color: navy;
}
</style>

// repromon_ng/src/app/components/app-header/app-header.component.ts
import { Component, Input, OnInit} from '@angular/core';
import { DatePipe } from '@angular/common';
import { AppConfig } from '../../config/AppConfig';
import { LoginService } from '../../service/LoginService';

@Component({
  selector: 'app-header',
  templateUrl: './app-header.component.html',
  styleUrls: ['./app-header.component.css']
})
export class AppHeaderComponent {
  @Input() screenName: string = '';
  @Input() firstName: string = '';
  @Input() lastName: string = '';
  currentTime: string | null;
  currentUser: any;

  constructor(private datePipe: DatePipe,
              private loginService: LoginService) {
    this.screenName = '';
    this.currentTime = '';
    this.currentUser = {};
  }

  ngOnInit(): void {
    console.log("ngOnInit()")
    this.updateTime();
    setInterval(() => this.updateTime(), 1000);
    this.getCurrentUser();
  }

  updateTime(): void {
    const now = new Date();
    this.currentTime = this.datePipe.transform(now, 'yyyy/MM/dd HH:mm:ss');
  }

  async getCurrentUser(): Promise<void> {
    try {
      this.currentUser = await this.loginService.getCurrentUser().toPromise();
      AppConfig.CURRENT_USER = this.currentUser;
      console.log('set AppConfig.CURRENT_USER=' + JSON.stringify(AppConfig.CURRENT_USER));
    } catch (error) {
      console.error('Failed to get current user:', error);
    }
  }

}

<div class="header" style="display: flex; justify-content: space-between;">
  <div>
    <p>&nbsp;<b>ReproMon: </b>{{ screenName }}</p>
  </div>
  <div>
    <p>
      <b>Time:</b> {{ currentTime | date: 'yyyy/MM/dd HH:mm:ss' }} &nbsp;&nbsp;
      <b>User:</b> {{ currentUser?.first_name }} {{ currentUser?.last_name }}&nbsp;
    </p>
  </div>
</div>
