// repromon_vue/src/components/StudyHeader.vue
<template>
  <table style="padding: 10px;">
    <tr>
      <td><b>Status:</b></td>
      <td>{{ studyHeader.status }}</td>
    </tr>
    <tr>
      <td><b>Study:</b></td>
      <td>{{ studyHeader.study }}</td>
    </tr>
    <tr>
      <td><b>Device:</b></td>
      <td>{{ studyHeader.device }}</td>
    </tr>
  </table>
</template>

<script>
import { FeedbackService } from '@/service/FeedbackService.js';

export default {
  props: {
    study_id: {
      type: Number,
      required: true,
    },
  },
  data() {
    return {
      studyHeader: {},
    };
  },
  mounted() {
    this.getStudyHeader();
  },
  methods: {
    async getStudyHeader() {
      console.log("getStudyHeader")
      try {
        this.studyHeader = await FeedbackService.getStudyHeader(this.study_id); // Replace 123 with the actual study ID
      } catch (error) {
        console.error('Failed to get study header:', error);
      }
    },
  },
};
</script>

// repromon_ng/src/app/components/study-header/study-header.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FeedbackService } from '../../service/FeedbackService';

@Component({
  selector: 'study-header',
  templateUrl: './study-header.component.html',
  styleUrls: ['./study-header.component.css']
})
export class StudyHeaderComponent implements OnInit {
  @Input() studyId: number = 0;
  studyHeader: any;

  constructor(private feedbackService: FeedbackService) {
    this.studyHeader = {};
  }

  ngOnInit(): void {
    this.getStudyHeader();
  }

  async getStudyHeader(): Promise<void> {
    try {
      this.studyHeader = await this.feedbackService.getStudyHeader(this.studyId).toPromise();
    } catch (error) {
      console.error('Failed to get study header:', error);
    }
  }
}

<table style="padding: 10px;">
  <tr>
    <td><b>Status:</b></td>
    <td>{{ studyHeader.status }}</td>
  </tr>
  <tr>
    <td><b>Study:</b></td>
    <td>{{ studyHeader.study }}</td>
  </tr>
  <tr>
    <td><b>Device:</b></td>
    <td>{{ studyHeader.device }}</td>
  </tr>
</table>
